name: Analysis

on:
  push:
    branches: [ main, master ]  
  pull_request:
    branches: [ main, master ]  

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml  

  dependency-check:
      name: OWASP Dependency-Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Run Dependency-Check
          uses: johannes-experiential-technology/dep-scan-action@v0.1.0
          with:
            scanpath: 'ToDoList'


