name: Analysis Code

on:
  push:
    branches: [ main, master ]  
  pull_request:
    branches: [ main, master ]  

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
         
          config: .semgrep.yml  
          output-format: "sarif"
          output-file: "semgrep-results.sarif"
