name: Analysis

on:
  push:
    branches: [ main, master ]  
  pull_request:
    branches: [ main, master ]  

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:

          config: .semgrep.yml  

          output-format: sarif
          output-file: semgrep-results.sarif

      - name: Upload SARIF results 
        if: always()  
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
